# Generated by Django 6.0 on 2026-02-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body_text',
            field=models.CharField(max_length=255),
        ),
    ]
